### ISSUE TITLE
Using HTB APIs by cURL command

### ISSUE THREAD

**Issue by D3vil0p3r** [mxrch/htb_api#1]
Hello,
is it possible to use those APIs by CURL command?

Furthermore, when you write as example `GET /api/vpnserver/status/all + api_token`, in particular where the API token must be placed?

**Comment by mxrch** [comment]
Hello, I don't know, this API is deprecated, please refer to the new HTB API documentation !

**Comment by D3vil0p3r** [comment]
> Hello, I don't know, this API is deprecated, please refer to the new HTB API documentation !

Do you mean this one: https://documenter.getpostman.com/view/13129365/TVeqbmeq#auth-info-60b37e03-af60-45c1-ad84-fb879f80cc65 ?

**Comment by D3vil0p3r** [comment]
I close the issue due to deprecated APIs.
